version: '3.7'

services:
  api:
    build: api
    ports:
      - 5000:5000 # flask default port
    environment:
      - PORT=5000
      - CLIENT_ORIGIN=http://localhost:1234
      # make sure the server views can make requests to itself; annoying and
      # needs to go once the FE is hooked up
      - HOST=127.0.0.1
    command: [ "flask", "--app", "app/main.py", "--debug", "run", "-h", "0.0.0.0" ]
    volumes:
      - ./api/app:/server/app
  client:
    # long format here for multi-stage build; stop at empty development
    # stage in dockerfile so the container doesn't try to do production
    # builds when it starts up here
    build:
      context: ./client
      target: development
    ports:
      - 1234:1234 # parcel's preferred port
    command: [ "yarn", "start" ]
    volumes:
      - ./client/src:/app/src
      - ./client/package.json:/app/package.json
      - ./client/yarn.lock:/app/yarn.lock
      - ./client/tsconfig.json:/app/tsconfig.json
